language: node_js
cache: npm
notifications:
  email: false
env:
  - TEST=test
node_js:
  - lts/*
  - node
install: npm install
script:
  - npm run validate
after_success:
  - mv coverage/coverage-final.json coverage/coverage.json
branches:
  only:
    - master
    - next
    - beta
    - alpha

jobs:
  include:
    - stage: release
      # if: branch = master AND commit_message =~ /^[0-9]*\.[0-9]*\.[0-9]*$/
      if: branch = master
      node_js: lts/*
      env:
        - PRODUCTION=production
      script:
        - npm run build
      after_success:
        - echo "Deploying to npm ..."
        - npm run semantic-release

    - stage: deploy
      if: branch = master
      node_js: lts/*
      env:
        - PRODUCTION=production
      script:
        - echo "Deploying to github pages ..."
        - npm run storybook:build
      deploy:
        provider: pages
        local_dir: .storybook-static
        cleanup: false
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
